"""Regenerate `data/cuad_clause_definitions.json` from the local CUAD dataset.

Fix #1 supplies the model the canonical CUAD `Details:` clause definition (the
same input the published CUAD baselines are queried with). To keep that text
auditable and NEVER hand-authored, the definitions are extracted verbatim from
the `theatticusproject/cuad-qa` question field and pinned to a committed JSON.

The `Details:` string is constant per clause type across all contracts, so we
assert that invariant and fail loudly if a clause type yields more than one
distinct definition (a sign the dataset format drifted).

Usage:
  python -m scripts.refresh_cuad_definitions                 # reads data/cuad
  python -m scripts.refresh_cuad_definitions --dataset data/cuad --out data/cuad_clause_definitions.json
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from scripts.eval_cuad_spans import (
    DEFAULT_CLAUSE_TYPES,
    _extract_clause_phrase_from_question,
    _extract_definition_from_question,
    _normalize_clause_question_name,
)


def build_definitions(dataset_path: Path) -> dict[str, str]:
    """Extract {clause_type: Details-definition} from the CUAD-QA dataset.

    Raises ValueError if a clause type has >1 distinct definition (drift) or if
    any `DEFAULT_CLAUSE_TYPES` member is missing from the dataset.
    """
    from datasets import load_from_disk  # type: ignore

    ds = load_from_disk(str(dataset_path))
    splits = list(ds.values()) if hasattr(ds, "values") else [ds]

    seen: dict[str, set[str]] = {}
    for split in splits:
        for rec in split:
            phrase = _extract_clause_phrase_from_question(str(rec["question"]))
            if phrase is None:
                continue
            ct = _normalize_clause_question_name(phrase)
            if ct is None:
                continue
            definition = _extract_definition_from_question(str(rec["question"]))
            if definition:
                seen.setdefault(ct, set()).add(definition)

    out: dict[str, str] = {}
    for ct in DEFAULT_CLAUSE_TYPES:
        variants = seen.get(ct)
        if not variants:
            raise ValueError(f"no Details definition found for clause type {ct!r}")
        if len(variants) > 1:
            raise ValueError(
                f"clause type {ct!r} has {len(variants)} distinct definitions; "
                "the dataset format may have drifted — inspect before pinning."
            )
        out[ct] = next(iter(variants))
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Regenerate CUAD clause definitions.")
    ap.add_argument("--dataset", type=Path, default=Path("data/cuad"))
    ap.add_argument("--out", type=Path, default=Path("data/cuad_clause_definitions.json"))
    args = ap.parse_args(argv)

    try:
        definitions = build_definitions(args.dataset)
    except (ValueError, OSError) as exc:
        print(f"refresh failed: {exc}", file=sys.stderr)
        return 1

    payload = {
        "_provenance": (
            "Verbatim Details: text from the theatticusproject/cuad-qa question "
            "field. Regenerated by scripts/refresh_cuad_definitions.py. "
            "Do NOT hand-edit."
        ),
        "definitions": definitions,
    }
    args.out.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {len(definitions)} definitions to {args.out}")
    for k, v in definitions.items():
        print(f"  {k}: {v[:80]}...")
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
